services:
  vault:
    run_as_root: true
    expose_ports:
      - 8200
      - 8201
      - 8501
      - 80
      - 443
    cap_add:
      - IPC_LOCK
      - NET_ADMIN
      - NET_RAW
    secured_services:  # Liste simple de services
      - vault-${BRANCH_NAME}
      - consul-${BRANCH_NAME}
      - mongodb-${BRANCH_NAME}
      - api-mongodb-${BRANCH_NAME}
      - postgresql-${BRANCH_NAME}
      - api-postgresql-${BRANCH_NAME}
      - api-gateway-${BRANCH_NAME}
      - frontend-${BRANCH_NAME}
      - reverse-proxy-${BRANCH_NAME}
      - zookeeper-${BRANCH_NAME}
      - kafka-${BRANCH_NAME}
      - minio-${BRANCH_NAME}
      - api-minio-${BRANCH_NAME}
      - mlflow-${BRANCH_NAME}
    env_vars:
      SERVICE_NAME: vault-${BRANCH_NAME}
      SERVICE_NAME: vault-${BRANCH_NAME}
      SERVICE_PORT: 8200
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_USERNAME: vault
      VAULT_PASSWORD: vault
      CONSUL_SERVER_HOST: consul-${BRANCH_NAME}
      CONSUL_SERVER_PORT: 8501
  consul:
    env_vars:
      SERVICE_NAME: consul-${BRANCH_NAME}
      SERVICE_PORT: 8500
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_USERNAME: consul
      VAULT_PASSWORD: consul
      CONSUL_SERVER_HOST: consul-${BRANCH_NAME}
      CONSUL_SERVER_PORT: 8501
      INITIALIZED: false
  postgresql:
    env_vars:
      SERVICE_NAME: postgresql-${BRANCH_NAME}
      SERVICE_PORT: 5432
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_USERNAME: postgresql
      VAULT_PASSWORD: postgresql
      PORT: 5432
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
  api-postgresql:
    env_vars:
      SERVICE_NAME: api-postgresql-${BRANCH_NAME}
      SERVICE_PORT: 8080
      POSTGRESQL_SERVICE_NAME: postgresql-${BRANCH_NAME}
      POSTGRESQL_SERVICE_PORT: 5432
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_USERNAME: api-postgresql
      VAULT_PASSWORD: api-postgresql
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
      API_GATEWAY_SERVICE_NAME: api-gateway-${BRANCH_NAME}
  mongodb:
    env_vars:
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_USERNAME: mongodb
      VAULT_PASSWORD: mongodb
      PORT: 27017
      SERVICE_NAME: mongodb-${BRANCH_NAME}
  api-mongodb:
    env_vars:
      SERVICE_NAME: api-mongodb-${BRANCH_NAME}
      SERVICE_PORT: 8000
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_USERNAME: api-mongodb
      VAULT_PASSWORD: api-mongodb
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
      MONGODB_SERVICE_NAME: mongodb-${BRANCH_NAME}
      MONGODB_SERVICE_PORT: 27017
      API_GATEWAY_SERVICE_NAME: api-gateway-${BRANCH_NAME}
  minio:
    env_vars:
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_USERNAME: minio
      VAULT_PASSWORD: minio
      PORT: 9010
      GUI_PORT: 9011
      SERVICE_NAME: minio-${BRANCH_NAME}
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
  api-minio:
    env_vars:
      SERVICE_NAME: api-minio-${BRANCH_NAME}
      SERVICE_PORT: 8020
      SERVICE_VERSION: v0.0.1
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_USERNAME: api-minio
      VAULT_PASSWORD: api-password
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
      MINIO_SERVICE_NAME: minio-${BRANCH_NAME}
      MINIO_SERVICE_PORT: 9010
      API_GATEWAY_SERVICE_NAME: api-gateway-${BRANCH_NAME}
  api-gateway:
    env_vars:
      SERVICE_NAME: api-gateway-${BRANCH_NAME}
      SERVICE_PORT: 9000
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
      VAULT_USERNAME: api-gateway
      VAULT_PASSWORD: api-gateway
      API_MONGODB_SERVICE_NAME: api-mongodb-${BRANCH_NAME}
      API_MONGODB_SERVICE_PORT: 8000
      API_POSTGRESQL_SERVICE_NAME: api-postgresql-${BRANCH_NAME}
      API_POSTGRESQL_SERVICE_PORT: 8010
  mlflow:
    env_vars:
      SERVICE_NAME: mlflow-${BRANCH_NAME}
      SERVICE_PORT: 8000
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_USERNAME: mlflow
      VAULT_PASSWORD: mlflow
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
      MONGODB_SERVICE_NAME: mongodb-${BRANCH_NAME}
      MONGODB_SERVICE_PORT: 27017
      MINIO_SERVICE_NAME: minio-${BRANCH_NAME}
      MINIO_SERVICE_PORT: 9010
  frontend:
    env_vars:
      SERVICE_NAME: frontend-${BRANCH_NAME}
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
      VAULT_USERNAME: frontend
      VAULT_PASSWORD: frontend
      API_GATEWAY_SERVICE_NAME: api-gateway-${BRANCH_NAME}
      API_GATEWAY_SERVICE_PORT: 8000
  reverse-proxy:
    env_vars:
      SERVICE_NAME: reverse-proxy-${BRANCH_NAME}
      VAULT_ADDR: https://vault-${BRANCH_NAME}:8200
      VAULT_SERVICE_NAME: vault-${BRANCH_NAME}
      VAULT_USERNAME: reverse-proxy
      VAULT_PASSWORD: reverse-proxy
      FRONTEND_SERVICE_NAME: frontend-${BRANCH_NAME}
      FRONTEND_SERVICE_PORT: 3000
      API_GATEWAY_SERVICE_NAME: api-gateway-${BRANCH_NAME}
      API_GATEWAY_SERVICE_PORT: 9000
