apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://${PROMETHEUS_SERVICE_NAME}:${PROMETHEUS_SERVICE_PORT}
    isDefault: true
    basicAuth: true
    basicAuthUser: ${PROMETHEUS_USER_NAME}
    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_USER_PASSWORD}
    jsonData:
      tlsSkipVerify: false
      tlsAuthWithCACert: true
      tlsCACert: ${PROMETHEUS_GRAFANA_CA_PATH}

    