---
- name: Include Helm install task
  include_tasks: helm.yml
  tags: helm

- name: Template cilium
  include_tasks: cilium.yml
  tags: cilium

- name: Template metallb
  include_tasks: metallb.yml
  tags: metallb

- name: Template openebs
  include_tasks: openebs.yml
  tags: openebs
