export const rakutenCategories = [
  { id: 10, name: "Livre occasion" },
  { id: 40, name: "Jeu vidéo, accessoire tech." },
  { id: 50, name: "Accessoire Console" },
  { id: 60, name: "Console de jeu" },
  { id: 1140, name: "Figurine" },
  { id: 1160, name: "Carte Collection" },
  { id: 1180, name: "Jeu Plateau" },
  { id: 1280, name: "Jouet enfant, déguisement" },
  { id: 1281, name: "Jeu de société" },
  { id: 1300, name: "Jouet tech" },
  { id: 1301, name: "Paire de chaussettes" },
  { id: 1302, name: "Jeu extérieur, vêtement" },
  { id: 1320, name: "Autour du bébé" },
  { id: 1560, name: "Mobilier intérieur" },
  { id: 1920, name: "Chambre" },
  { id: 1940, name: "Cuisine" },
  { id: 2060, name: "Décoration intérieure" },
  { id: 2220, name: "Animal" },
  { id: 2280, name: "Revues et journaux" },
  { id: 2403, name: "Magazines, livres et BDs" },
  { id: 2462, name: "Jeu occasion" },
  { id: 2522, name: "Bureautique et papeterie" },
  { id: 2582, name: "Mobilier extérieur" },
  { id: 2583, name: "Autour de la piscine" },
  { id: 2585, name: "Bricolage" },
  { id: 2705, name: "Livre neuf" },
  { id: 2905, name: "Jeu PC" }
];