mayastor:
  tolerations:
    - key: "openebs.io/storage"
      operator: "Equal"
      value: "mayastor"
      effect: "NoSchedule"
  csi:
    node:
      topology:
        nodeSelector: true
        segments:
          openebs.io/csi-node: mayastor
# Désactiver les composants non nécessaires
localpv-provisioner:
  enabled: false
minio:
  enabled: false
openebs-api:
  enabled: false
ndm:
  enabled: false
ndm-operator:
  enabled: false
