apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-1
  namespace: openebs
provisioner: io.openebs.csi-mayastor
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  protocol: nvmf
  repl: "1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-3
  namespace: openebs
provisioner: io.openebs.csi-mayastor
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  protocol: nvmf
  repl: "3"
  thin: "true"
  ioTimeout: "30"
