localpv-provisioner:
  enabled: false
mayastor:
  csi:
    node:
      topology:
        nodeSelector: true
        segments:
          openebs.io/csi-node: mayastor
  tolerations:
  - effect: NoSchedule
    key: openebs.io/storage
    operator: Equal
    value: mayastor
minio:
  enabled: false
ndm:
  enabled: false
ndm-operator:
  enabled: false
openebs-api:
  enabled: false
