#from dotenv import load_dotenv
import os

API_GATEWAY_HOST = os.getenv("API_GATEWAY_HOST")
INTERNAL_ENDPOINT_URL = os.getenv("API_POSTGRESQL_INTERNAL_ENDPOINT_URL")
PROTECTED_ENDPOINT_URL = os.getenv("API_POSTGRESQL_PROTECTED_ENDPOINT_URL")
DATABASE_URL = os.getenv("API_POSTGRESQL_DATABASE_URL")
SECRET_KEY = os.getenv("API_POSTGRESQL_SECRET_KEY")
INTERNAL_SECRET_KEY = os.getenv("API_POSTGRESQL_INTERNAL_SECRET_KEY")
ALGORITHM = os.getenv("API_POSTGRESQL_ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("API_POSTGRESQL_ACCESS_TOKEN_EXPIRE_MINUTES"))

POSTGRESQL_API_POSTGRESQL_CA_PATH = os.getenv("POSTGRESQL_API_POSTGRESQL_CA_PATH")
POSTGRESQL_API_POSTGRESQL_CERT_PATH = os.getenv("POSTGRESQL_API_POSTGRESQL_CERT_PATH")
POSTGRESQL_API_POSTGRESQL_KEY_PATH = os.getenv("POSTGRESQL_API_POSTGRESQL_KEY_PATH")


POSTGRESQL_SERVICE_PORT = os.getenv("POSTGRESQL_SERVICE_PORT")
POSTGRESQL_SERVICE_NAME = os.getenv("POSTGRESQL_SERVICE_NAME")
POSTGRESQL_USER = os.getenv("POSTGRESQL_API_POSTGRESQL_USER")
POSTGRESQL_PASSWORD = os.getenv("POSTGRESQL_API_POSTGRESQL_PASSWORD")
POSTGRESQL_DATABASE = os.getenv("POSTGRESQL_API_POSTGRESQL_DATABASE")
