[pytest]
testpaths =
    test/entity/test_user.py
    test/entity/test_flow_ad.py
    test/entity/test_get_categories.py
    test/entity/test_replicate.py
    test/entity/test_image.py
    test/entity/test_search_mongodb.py