from functools import lru_cache
import os
from pydantic_settings import BaseSettings

DEFAULT_TOKEN_DURATION_IN_MINUTES = 60
DEFAULT_MLFLOW_TEXT_CLASSIFIER_MODEL_VERSION = 1
DEFAULT_MLFLOW_TEXT_TRANSLATOR_MODEL_VERSION = 1
DEFAULT_MLFLOW_TEXT_LANGUAGE_DETECTOR_MODEL_VERSION = 1


class Settings(BaseSettings):
    SERVICE_VERSION: str = os.getenv("SERVICE_VERSION", default="SERVICE_VERSION")
    API_GATEWAY_HOST: str = os.getenv("API_GATEWAY_HOST", default="API_GATEWAY_HOST")
    INTERNAL_ENDPOINT_URL: str = os.getenv(
        "API_MINIO_INTERNAL_ENDPOINT_URL", default="INTERNAL_ENDPOINT_URL"
    )
    PROTECTED_ENDPOINT_URL: str = os.getenv(
        "API_MINIO_PROTECTED_ENDPOINT_URL", default="PROTECTED_ENDPOINT_URL"
    )
    DATABASE_URL: str = os.getenv("API_MINIO_DATABASE_URL", default="DATABASE_URL")
    SECRET_KEY: str = os.getenv("API_MINIO_SECRET_KEY", default="SECRET_KEY")
    INTERNAL_SECRET_KEY: str = os.getenv(
        "API_MINIO_INTERNAL_SECRET_KEY", default="INTERNAL_SECRET_KEY"
    )
    ALGORITHM: str = os.getenv("API_MINIO_ALGORITHM", default="ALGORITHM")
    ACCESS_TOKEN_EXPIRE_MINUTES: int = (
        int(os.getenv("API_MINIO_ACCESS_TOKEN_EXPIRE_MINUTES"))
        if os.getenv("API_MINIO_ACCESS_TOKEN_EXPIRE_MINUTES")
        else DEFAULT_TOKEN_DURATION_IN_MINUTES
    )
    MLFLOW_ADDR: str = os.getenv("MLFLOW_ADDR", default="MLFLOW_ADDR")
    MLFLOW_USERNAME: str = os.getenv("MLFLOW_USERNAME", default="MLFLOW_USERNAME")
    MLFLOW_PASSWORD: str = os.getenv("MLFLOW_PASSWORD", default="MLFLOW_PASSWORD")
    MLFLOW_SERVICE_NAME: str = os.getenv(
        "MLFLOW_SERVICE_NAME", default="MLFLOW_SERVICE_NAME"
    )
    MLFLOW_MODEL_NAME: str = os.getenv("MLFLOW_MODEL_NAME", default="MLFLOW_MODEL_NAME")
    MLFLOW_MODEL_VERSION: int = (
        int(os.getenv("MLFLOW_MODEL_VERSION"))
        if os.getenv("MLFLOW_MODEL_VERSION")
        else DEFAULT_TOKEN_DURATION_IN_MINUTES
    )
    MLFLOW_TEXT_CLASSIFIER_MODEL_NAME: str = os.getenv(
        "MLFLOW_TEXT_CLASSIFIER_MODEL_NAME", default="MLFLOW_TEXT_CLASSIFIER_MODEL_NAME"
    )
    MLFLOW_TEXT_CLASSIFIER_MODEL_VERSION: int = (
        int(os.getenv("MLFLOW_TEXT_CLASSIFIER_MODEL_VERSION"))
        if os.getenv("MLFLOW_TEXT_CLASSIFIER_MODEL_VERSION")
        else DEFAULT_MLFLOW_TEXT_CLASSIFIER_MODEL_VERSION
    )
    MLFLOW_TEXT_TRANSLATOR_MODEL_NAME: str = os.getenv(
        "MLFLOW_TEXT_TRANSLATOR_MODEL_NAME", default="MLFLOW_TEXT_TRANSLATOR_MODEL_NAME"
    )
    MLFLOW_TEXT_TRANSLATOR_MODEL_VERSION: int = (
        int(os.getenv("MLFLOW_TEXT_TRANSLATOR_MODEL_VERSION"))
        if os.getenv("MLFLOW_TEXT_TRANSLATOR_MODEL_VERSION")
        else DEFAULT_MLFLOW_TEXT_TRANSLATOR_MODEL_VERSION
    )
    MLFLOW_TEXT_LANGUAGE_DETECTOR_MODEL_NAME: str = os.getenv(
        "MLFLOW_TEXT_LANGUAGE_DETECTOR_MODEL_NAME",
        default="MLFLOW_TEXT_LANGUAGE_DETECTOR_MODEL_NAME",
    )
    MLFLOW_TEXT_LANGUAGE_DETECTOR_MODEL_VERSION: int = (
        int(os.getenv("MLFLOW_TEXT_LANGUAGE_DETECTOR_MODEL_VERSION"))
        if os.getenv("MLFLOW_TEXT_LANGUAGE_DETECTOR_MODEL_VERSION")
        else DEFAULT_MLFLOW_TEXT_LANGUAGE_DETECTOR_MODEL_VERSION
    )
    MLFLOW_TEXT_LANGUAGE_DETECTOR_ARTIFACT_RUN_ID: str = os.getenv(
        "MLFLOW_TEXT_LANGUAGE_DETECTOR_ARTIFACT_RUN_ID",
        default="MLFLOW_TEXT_LANGUAGE_DETECTOR_ARTIFACT_RUN_ID",
    )
    MLFLOW_TEXT_LANGUAGE_DETECTOR_INDEX_ARTIFACT_PATH: str = os.getenv(
        "MLFLOW_TEXT_LANGUAGE_DETECTOR_INDEX_ARTIFACT_PATH",
        default="MLFLOW_TEXT_LANGUAGE_DETECTOR_INDEX_ARTIFACT_PATH",
    )
    MLFLOW_TEXT_TRANSLATOR_ARTIFACT_RUN_ID: str = os.getenv(
        "MLFLOW_TEXT_TRANSLATOR_ARTIFACT_RUN_ID",
        default="MLFLOW_TEXT_TRANSLATOR_ARTIFACT_RUN_ID",
    )
    MLFLOW_TEXT_TRANSLATOR_CACHE_ARTIFACT_PATH: str = os.getenv(
        "MLFLOW_TEXT_TRANSLATOR_CACHE_ARTIFACT_PATH",
        default="MLFLOW_TEXT_TRANSLATOR_CACHE_ARTIFACT_PATH",
    )
    MLFLOW_LOCAL_ARTIFACT_DIRECTORY_PATH: str = os.getenv(
        "MLFLOW_LOCAL_ARTIFACT_DIRECTORY_PATH",
        default="MLFLOW_LOCAL_ARTIFACT_DIRECTORY_PATH",
    )


settings = Settings()


@lru_cache
def get_settings():
    return Settings()
