---
- name: Ensure conflicting containerd package is removed
  apt:
    name: containerd
    state: absent
  become: yes
  tags: install

- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes
  tags: install

- name: Ensure Docker service is running and enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
  tags: install

- name: Ensure dependencies for Kubernetes repository are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
  tags: install

- name: Ensure Kubernetes apt repository key is present
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present
  become: yes
  tags: install

- name: Ensure Kubernetes apt repository is configured
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
    state: present
    filename: kubernetes
  become: yes
  tags: install

- name: Ensure apt package index is updated
  apt:
    update_cache: yes
  become: yes
  tags: install

- name: Ensure Kubernetes components are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubelet
    - kubeadm
    - kubectl
  tags: install

- name: Check if swap is enabled
  command: swapon --show
  register: swap_status
  changed_when: false
  ignore_errors: yes
  tags: install

- name: Disable swap if enabled
  command: swapoff -a
  become: yes
  when: swap_status.rc == 0
  tags: install

- name: Remove swap entry from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s.*)$'
    replace: '# \1'
  become: yes
  when: swap_status.rc == 0
  tags: install

- name: Add kubernetes-master entry to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars['master1']['ansible_default_ipv4']['address'] }} kubernetes-master"
    state: present
  become: yes
  tags: install

- name: Pull Kubernetes images
  command: kubeadm config images pull
  become: yes
  tags: install

- name: Initialize Kubernetes cluster on first master
  command: kubeadm init --ignore-preflight-errors=all --control-plane-endpoint "kubernetes-master:6443" --upload-certs
  when: inventory_hostname == 'master1'
  register: init_output
  tags: install

- name: Ensure .kube directory exists
  file:
    path: /root/.kube
    state: directory
    mode: '0755'
  when: inventory_hostname == 'master1'
  become: yes
  tags: install

- name: Ensure kubeconfig is configured
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == 'master1'
  become: yes
  tags: install
