---
- name: Include installation tasks
  include_tasks: install.yml
  tags: install

- name: Include Label Nodes tasks
  include_tasks: label_nodes.yml
  tags: label_nodes

- name: Include Namespaces tasks
  include_tasks: namespaces.yml
  when: create_namespaces | default(false)
  tags: namespaces 

- name: Include CNI tasks
  include_tasks: cni.yml
  when: install_cni | default(false)
  tags: cni

- name: Include MetalLB tasks
  include_tasks: metallb.yml
  when: install_metallb | default(false)
  tags: metallb

- name: Include Dashboard tasks
  include_tasks: dashboard.yml
  when: install_dashboard | default(false)
  tags: dashboard

# - name: Include CSI tasks
#   include_tasks: csi.yml
#   when: install_csi | default(false)
#   tags: csi
