---
# Récupère la liste des nœuds du cluster
- name: Get list of nodes in the cluster
  command: kubectl get nodes -o jsonpath='{.items[*].metadata.name}'
  register: k8s_nodes
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false
  tags: taint_nodes

# Applique les taints aux nœuds réseau (uniquement s'ils existent dans le cluster)
- name: Taint network nodes
  command: kubectl taint nodes {{ item }} node-role.kubernetes.io/network=true:NoSchedule --overwrite
  loop: "{{ groups['networks'] | default([]) }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: item in k8s_nodes.stdout.split()
  tags: taint_nodes

# # Applique les taints aux nœuds master (optionnel, selon vos besoins)
# - name: Taint master nodes
#   command: kubectl taint nodes {{ item }} node-role.kubernetes.io/master=true:NoSchedule --overwrite
#   loop: "{{ groups['masters'] | default([]) }}"
#   delegate_to: "{{ groups['masters'][0] }}"
#   run_once: true
#   become: yes
#   environment:
#     KUBECONFIG: /etc/kubernetes/admin.conf
#   when: item in k8s_nodes.stdout.split()
#   tags: taint_nodes

# # Applique les taints aux nœuds worker (optionnel, selon vos besoins)
# - name: Taint worker nodes
#   command: kubectl taint nodes {{ item }} node-role.kubernetes.io/worker=true:NoSchedule --overwrite
#   loop: "{{ groups['workers'] | default([]) }}"
#   delegate_to: "{{ groups['masters'][0] }}"
#   run_once: true
#   become: yes
#   environment:
#     KUBECONFIG: /etc/kubernetes/admin.conf
#   when: item in k8s_nodes.stdout.split()
#   tags: taint_nodes

# Applique les taints aux nœuds data (optionnel, selon vos besoins)
- name: Taint data nodes
  command: kubectl taint nodes {{ item }} node-role.kubernetes.io/data=true:NoSchedule --overwrite
  loop: "{{ groups['datas'] | default([]) }}"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: item in k8s_nodes.stdout.split()
  tags: taint_nodes
