---
- name: Check Mayastor pods status
  command: kubectl -n mayastor get pods
  register: mayastor_pods
  when: inventory_hostname == 'master1'
  become: yes
  tags: test_csi

- name: Display Mayastor pods status
  debug:
    var: mayastor_pods.stdout_lines
  when: inventory_hostname == 'master1'
  tags: test_csi

- name: Check Mayastor configuration
  command: kubectl -n mayastor get all
  register: mayastor_config
  when: inventory_hostname == 'master1'
  become: yes
  tags: test_csi

- name: Display Mayastor configuration
  debug:
    var: mayastor_config.stdout_lines
  when: inventory_hostname == 'master1'
  tags: test_csi
