version: "1.0"
name: "infra-webapp"
description: "Infrastructure pour une application web avec base de données"
networks:
  - name: "app-net"
    description: "Réseau pour l'application"
    type: "nat"
    subnet: "192.168.100.1/24"
    dhcp:
      start: "192.168.100.2"
      end: "192.168.100.200"
    dns:
      enabled: true
      domain: "app.local"
      servers: ["8.8.8.8"]
vms:
  - name: "frontend-origin"
    cpu: 4
    ram: 12288
    disk_size: 20
    networks:
      - name: "app-net"
        ip: "192.168.100.10"  # Adresse IP statique
    cloud_init:
      iso: "ubuntu-24.04.1-live-server-amd64.iso"
      meta_data:
        instance-id: frontend-origin
        local-hostname: frontend-origin
      user_data:
        #cloud-config
        autoinstall:
          version: 1
          identity:
            hostname: frontend-origin
            username: ubuntu
            password: "$6$azI.phbtXYmpiU7T$pNQ7Ogdk9KWYnhPw4G/7p/VnxQ.vMmI/Xs56wWvhDmoEe7VRMRoSRhiA6cONZOU./N9WxdQmxuefaJDG4qxwU."
          ssh:
            install-server: true
            authorized-keys:
              - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBCp7UHEy9aOkk7N6NixYu+gxnyuUHEyjKKE3qk7YijR2dKZHWREsWVr/H6ibL50iZx8ubbTCyNCwhEnyX8J2DipJHtlfw0c2CYj1JW4DMnhQ7P6Cur0dMnPOhu3l1fg9WeEEAfKPm6D9OszWCg/A6Q6dDXDYv0T5WlUiEpnGvJsAlQqOJ64wx75LwwBXEqC089T5lZE50gisDXjkwNf9HFvEPLdUmxKG5s9ttcR8M5/BHJNB0kR+pGaY9QPG67CFchgSFpPtj+Kn/go4uDuv4TrpxWrcvOuLRK7w3ssEGREyVIOmhEJytKkOBnkgAPTadm0LY4UmnJQTH2n2ywkVm51WrgJbwsZ/6YonewGJxJLGsuQ/BSQ8VYrVZQ9Vu6q9mOJd1ORhRjjvtEpk1PpbAGmKESDEbElk19OY1W1WhREVrTjKlmn5sXjngYDQlkBuQfolIbx+7mqAsbIt6LU0UE886WIdyhXUY1ZoBpVNXlntS7WgR+kCcjL8jzxhUdtTCKFHjJhtQDUgEjkCez4lyVB7PRQRDX3Hp6qydL+wsC8LuuJfOb1CbkTFBqYZp1ZTYK1Thfy9USdYzQ3S+/wcUTlOCLzTtfPaY8oVhrBoPITcZsd+aut1QW+71L9h7eRwKYEK9O1NmQUDAagrfisPDjZahPD6aLwnAm5mmJICNiQ== Philippe-RM@github/131196788"
          storage:
            layout:
              name: lvm
          network:
            version: 2
            ethernets:
              enp1s0:
                dhcp4: false
                addresses: [192.168.100.10/24]
                gateway4: 192.168.100.1
                nameservers:
                  addresses: [8.8.8.8, 8.8.4.4]
          packages:
            - nginx
            - fcgiwrap
            - qemu-guest-agent
          late-commands:
            - |
              cat << 'EOF' > /target/etc/systemd/system/start-ssh.service
              [Unit]
              Description=Start SSH Service
              After=network.target

              [Service]
              Type=simple
              ExecStart=/bin/bash /usr/local/bin/start-ssh.sh
              User=root
              Restart=always

              [Install]
              WantedBy=multi-user.target
              EOF
            - |
              cat << 'EOF' > /target/usr/local/bin/start-ssh.sh
              #!/bin/bash
              # Boucle infinie pour vérifier et redémarrer le service SSH si nécessaire
              while true; do
                if [ "$(systemctl is-active ssh)" != "active" ]; then
                  systemctl start ssh
                fi
                if [ "$(systemctl is-enabled ssh)" != "enabled" ]; then
                  systemctl enable ssh
                fi
                sleep 10
              done
              EOF
            - chmod +x /target/usr/local/bin/start-ssh.sh
            - chroot /target systemctl enable start-ssh.service
            - |
              cat << 'EOF' > /target/etc/systemd/system/start-qemu-guest-agent.service
              [Unit]
              Description=Start QEMU Guest Agent Service
              After=network.target

              [Service]
              Type=simple
              ExecStart=/bin/bash /usr/local/bin/start-qemu-guest-agent.sh
              User=root
              Restart=always

              [Install]
              WantedBy=multi-user.target
              EOF
            - |
              cat << 'EOF' > /target/usr/local/bin/start-qemu-guest-agent.sh
              #!/bin/bash
              # Boucle infinie pour vérifier et redémarrer le service qemu-guest-agent si nécessaire
              while true; do
                if [ "$(systemctl is-active qemu-guest-agent)" != "active" ]; then
                  systemctl start qemu-guest-agent
                fi
                if [ "$(systemctl is-enabled qemu-guest-agent)" != "enabled" ]; then
                  systemctl enable qemu-guest-agent
                fi
                sleep 10
              done
              EOF
            - chmod +x /target/usr/local/bin/start-qemu-guest-agent.sh
            - chroot /target systemctl enable start-qemu-guest-agent.service
            - |
              # Définir un mot de passe pour l'utilisateur root
              echo 'root:monmotdepasse' | chroot /target chpasswd
            - |
              # Créer un fichier de configuration pour le service
              cat << 'EOF' > /target/etc/root_service.conf
              # Fichier de configuration pour le service root
              password="monmotdepasse"
              EOF
            - chmod 600 /target/etc/root_service.conf
            - chown root:root /target/etc/root_service.conf
      disks:
        - name: system
          path: "/var/lib/libvirt/images/frontend-origin.qcow2"
          size: 20
    copy_files:
      - source: nginx/
        destination: /opt/test/
    post_install_scripts:
      - ssh/enable.sh
      - nginx/install.sh

  - name: "frontend-clone"
    cpu: 4
    ram: 12288
    disk_size: 20
    networks:
      - name: "app-net"
        ip: "192.168.100.11"  # Adresse IP statique
    clone_init:
      source_vm: "frontend-origin"
      meta_data:
        instance-id: frontend-clone
        local-hostname: frontend-clone
      user_data:
        #cloud-config
        autoinstall:
          version: 1
          identity:
            hostname: frontend-clone
            username: ubuntu
            password: "ubuntu"
            # password: "$6$azI.phbtXYmpiU7T$pNQ7Ogdk9KWYnhPw4G/7p/VnxQ.vMmI/Xs56wWvhDmoEe7VRMRoSRhiA6cONZOU./N9WxdQmxuefaJDG4qxwU."
          ssh:
            install-server: true
            authorized-keys:
              - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBCp7UHEy9aOkk7N6NixYu+gxnyuUHEyjKKE3qk7YijR2dKZHWREsWVr/H6ibL50iZx8ubbTCyNCwhEnyX8J2DipJHtlfw0c2CYj1JW4DMnhQ7P6Cur0dMnPOhu3l1fg9WeEEAfKPm6D9OszWCg/A6Q6dDXDYv0T5WlUiEpnGvJsAlQqOJ64wx75LwwBXEqC089T5lZE50gisDXjkwNf9HFvEPLdUmxKG5s9ttcR8M5/BHJNB0kR+pGaY9QPG67CFchgSFpPtj+Kn/go4uDuv4TrpxWrcvOuLRK7w3ssEGREyVIOmhEJytKkOBnkgAPTadm0LY4UmnJQTH2n2ywkVm51WrgJbwsZ/6YonewGJxJLGsuQ/BSQ8VYrVZQ9Vu6q9mOJd1ORhRjjvtEpk1PpbAGmKESDEbElk19OY1W1WhREVrTjKlmn5sXjngYDQlkBuQfolIbx+7mqAsbIt6LU0UE886WIdyhXUY1ZoBpVNXlntS7WgR+kCcjL8jzxhUdtTCKFHjJhtQDUgEjkCez4lyVB7PRQRDX3Hp6qydL+wsC8LuuJfOb1CbkTFBqYZp1ZTYK1Thfy9USdYzQ3S+/wcUTlOCLzTtfPaY8oVhrBoPITcZsd+aut1QW+71L9h7eRwKYEK9O1NmQUDAagrfisPDjZahPD6aLwnAm5mmJICNiQ== Philippe-RM@github/131196788"
          storage:
            layout:
              name: lvm
          network:
            version: 2
            ethernets:
              enp1s0:
                dhcp4: false
                addresses: [192.168.100.11/24]
                gateway4: 192.168.100.1
                nameservers:
                  addresses: [8.8.8.8, 8.8.4.4]
          packages:
            - nginx
            - fcgiwrap
            - qemu-guest-agent
          shutdown: poweroff
          resize_partition:
            enable: true
            partition: '/dev/vda3'
            disk: '/dev/vda'
          resize_partition_with_fdisk:
            enable: true
          resize_logical_volume:
            enable: true
      disks:
        - name: system
          path: "/var/lib/libvirt/images/frontend-clone.qcow2"
          size: 40
