version: "1.0"
name: "infra-webapp"
description: "Infrastructure pour une application web avec base de données"
networks:
  - name: "ori-k8s"
    description: "Réseau pour le cluster Kubernetes"
    type: "nat"
    subnet: "192.168.100.1/24"
    dhcp:
      start: "192.168.100.2"
      end: "192.168.100.200"
    dns:
      enabled: true
      domain: "k8s.local"
      servers: ["8.8.8.8", "8.8.4.4"]
vms:
  - name: kubernetes-origin
    cpu: 4
    ram: 12288
    disk_size: 20
    networks:
      - name: "ori-k8s"
        ip: "192.168.100.10"  # Adresse IP statique
    cloud_init:
      iso: ubuntu-24.04.3-live-server-amd64.iso
      meta_data:
        instance-id: kubernetes-origin
        local-hostname: kubernetes-origin
      user_data:
        #cloud-config
        autoinstall:
          version: 1
          identity:
            hostname: kubernetes-origin
            username: ubuntu
            password: "$6$azI.phbtXYmpiU7T$pNQ7Ogdk9KWYnhPw4G/7p/VnxQ.vMmI/Xs56wWvhDmoEe7VRMRoSRhiA6cONZOU./N9WxdQmxuefaJDG4qxwU."
          ssh:
            install-server: true
            authorized-keys:
              - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9x/mtoDy50VqHXcDKVQPVNacZAhMtkECMO1qVInBMm+7WfXbguBRKAAvLEHMCuEjUolTlcU7gwOFCtgurgzuVFBHc03PGYQQpy2AsxxQfT52VxZWTgQRqKPT+sqdqniNDTKZMFynQ3F5xvCIfwST4C8nunnMVmb68NnT4hIlw2ZGO0GCE07cXxlYuLbigxtrpR4W/+BvAbESy6lGbEW4Ytjii6vP/UhUFQkdrW+btT8wAiyvl1pBfxsSsjrZDRk3BKM3KPH5eELbAkJynObri8svMB44YbXK3XKgDDq+0YHczdHHTT9X6UaUIALKKEXdDpHjEFrULfz8RobkyJ32+owe2mUCt86xmQMRLUpP5rdA7v7E3JVBlfWQwQzKZ8HgN1BqCFpMF8k44nWitdJQePnbV8PO658eyOlVPRQaNeJS8NhiI4U5ayuZhsvDzVgnhwhxOU29uHud73T60aDFgJWhJd6Id/l+PFhAt2UF+6QvIjC8lftNxo21jkVmn8NV6CuIkeHtacrKf0ynXIY9gVMzKrH1T3JGutKa+gA3us/FKgdn+7pDB8PUSPg59PCF/I5pgg11Z9ZhAPAVlA7Y6gO5UTl/dbgrzJaL9Xo3sIDXnTz+sZcHvPiu1sWcGaGrmrhmLkx7E6E/bg9cLDolxhghhuAxqECk4GeEIHC7y/w== philipperisser@msn.com"
          storage:
            layout:
              name: lvm
              sizing-policy: all
            disks:
              - name: system
                path: "/var/lib/libvirt/images/kubernetes-origin.qcow2"
                size: 30
                partition: "/dev/vda3"
                resize: true
                mount_point: "/"
                filesystem: ext4
                resize_config:
                  enable: true
                  partition: '/dev/vda3'
                  disk: '/dev/vda'
                  methods:
                    fdisk: true
                    lvm: true
          network:
            version: 2
            ethernets:
              enp1s0:
                dhcp4: false
                addresses: [192.168.100.10/24]
                gateway4: 192.168.100.1
                nameservers:
                  addresses: [8.8.8.8, 8.8.4.4]
          packages:
            - nginx
            - fcgiwrap
            - qemu-guest-agent
            - yq
            - cloud-guest-utils
            - docker.io

          late-commands:
            - |
              cat << 'EOF' > /target/etc/systemd/system/start-ssh.service
              [Unit]
              Description=Start SSH Service
              After=network.target
              [Service]
              Type=simple
              ExecStart=/bin/bash /usr/local/bin/start-ssh.sh
              User=root
              Restart=always
              [Install]
              WantedBy=multi-user.target
              EOF
            - |
              cat << 'EOF' > /target/usr/local/bin/start-ssh.sh
              #!/bin/bash
              # Boucle infinie pour vérifier et redémarrer le service SSH si nécessaire
              while true; do
                if [ "$(systemctl is-active ssh)" != "active" ]; then
                  systemctl start ssh
                fi
                if [ "$(systemctl is-enabled ssh)" != "enabled" ]; then
                  systemctl enable ssh
                fi
                sleep 10
              done
              EOF
            - chmod +x /target/usr/local/bin/start-ssh.sh
            - chroot /target systemctl enable start-ssh.service
            - |
              cat << 'EOF' > /target/etc/systemd/system/start-qemu-guest-agent.service
              [Unit]
              Description=Start QEMU Guest Agent Service
              After=network.target
              [Service]
              Type=simple
              ExecStart=/bin/bash /usr/local/bin/start-qemu-guest-agent.sh
              User=root
              Restart=always
              [Install]
              WantedBy=multi-user.target
              EOF
            - |
              cat << 'EOF' > /target/usr/local/bin/start-qemu-guest-agent.sh
              #!/bin/bash
              # Boucle infinie pour vérifier et redémarrer le service qemu-guest-agent si nécessaire
              while true; do
                if [ "$(systemctl is-active qemu-guest-agent)" != "active" ]; then
                  systemctl start qemu-guest-agent
                fi
                if [ "$(systemctl is-enabled qemu-guest-agent)" != "enabled" ]; then
                  systemctl enable qemu-guest-agent
                fi
                sleep 10
              done
              EOF
            - chmod +x /target/usr/local/bin/start-qemu-guest-agent.sh
            - chroot /target systemctl enable start-qemu-guest-agent.service
            - |
              # Définir un mot de passe pour l'utilisateur root
              echo 'root:monmotdepasse' | chroot /target chpasswd
            - |
              # Créer un fichier de configuration pour le service
              cat << 'EOF' > /target/etc/root_service.conf
              # Fichier de configuration pour le service root
              password="monmotdepasse"
              EOF
            - chmod 600 /target/etc/root_service.conf
            - chown root:root /target/etc/root_service.conf
    copy_files:
      - source: nginx/
        destination: /opt/
    post_install_scripts:
      - nginx/install.sh
