name: AVR25 Rakuten MLOps - CI
run-name: Test AVR25 Rakuten MLOps actions started by ${{ github.actor }}
on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  FORCE_COLOR: "1"
jobs:
  clear-containers:
    runs-on: [self-hosted, phil-host]
    strategy:
      matrix:
        service: [vault, consul, mongodb, api-mongodb, postgresql, api-postgresql, api-gateway, frontend, reverse-proxy, minio, api-minio, api-processing, api-image-processing, api-text-processing, mlflow, prometheus, grafana, alertmanager, redis, airflow-worker,airflow-scheduler,airflow-triggerer,airflow-api-server,airflow-dag-processor]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get version from file
        id: get_version
        run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT
      - name: Stop and remove containers
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          TAG="${BRANCH_NAME}-${VERSION}"
          docker stop ${{ matrix.service }}-${BRANCH_NAME}|| true
          docker rm ${{ matrix.service }}-${BRANCH_NAME} || true

  clear-network:
    runs-on: [self-hosted, phil-host]
    needs: [clear-containers]
    steps:
      - name: Remove Docker network
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          NETWORK_NAME="network-${BRANCH_NAME}"
          # docker network rm $NETWORK_NAME #|| true  # Ignore l'erreur si le réseau n'existe pas ou ne peut pas être supprimé
          if docker network inspect $NETWORK_NAME &> /dev/null; then
            docker network rm $NETWORK_NAME
          else
            echo "Réseau $NETWORK_NAME n'existe pas, pas besoin de le supprimer."
          fi

  create-network:
    runs-on: [self-hosted, phil-host]
    needs: [clear-containers, clear-network]
    steps:
      - name: Create Docker network
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          NETWORK_NAME="network-${BRANCH_NAME}"
          docker network create $NETWORK_NAME || true # Ignore if network exists

  build:
    runs-on: [self-hosted, phil-host]
    needs: [clear-containers]
    strategy:
      matrix:
        service: [vault, consul, mongodb, api-mongodb, postgresql, api-postgresql, api-gateway, frontend, reverse-proxy, minio, api-minio, api-processing, api-image-processing, api-text-processing, mlflow, prometheus, grafana, alertmanager, redis, airflow-worker,airflow-scheduler,airflow-triggerer,airflow-api-server,airflow-dag-processor]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get version from file
        id: get_version
        run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.16.0

      - name: Build services
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          TAG="${BRANCH_NAME}-${VERSION}"
          cd src/${{ matrix.service }}
          docker build -t ${{ matrix.service }}:$TAG .

  start-containers:
    runs-on: [self-hosted, phil-host]
    needs: [create-network, build]
    strategy:
      matrix:
        service: [vault, consul, mongodb, api-mongodb, postgresql, api-postgresql, api-gateway, frontend, reverse-proxy, minio, api-minio, api-processing, api-image-processing, api-text-processing, mlflow, prometheus, grafana, alertmanager, redis, airflow-worker,airflow-scheduler,airflow-triggerer,airflow-api-server,airflow-dag-processor]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get version from file
        id: get_version
        run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT

      - name: Start containers
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          TAG="${BRANCH_NAME}-${VERSION}"
          NETWORK_NAME="network-${BRANCH_NAME}"
          CONTAINER_NAME="${{ matrix.service }}-${BRANCH_NAME}"
          SERVICE="${{ matrix.service }}"
          CONFIG=$(yq eval ".services[\"$SERVICE\"]" "services_config.yaml")

          ENV_VARS=""
          # Traiter les env_vars existantes
          while read -r key value; do
              processed_value=$(echo "$value" | sed "s/\${BRANCH_NAME}/$BRANCH_NAME/g" | sed "s/\${VERSION}/$VERSION/g")
              echo "Clé: $key, Valeur: $processed_value"
              ENV_VARS+=" -e $key=$processed_value"
          done < <(yq eval ".services[\"$SERVICE\"].env_vars | to_entries | .[] | \"\(.key) \(.value)\"" "services_config.yaml")

          CAP_ADD=$(yq eval ".cap_add | join(\",\")" <<< "$CONFIG" || true)
          CAP_OPTIONS=""
          if [ "$CAP_ADD" != "null" ] && [ -n "$CAP_ADD" ]; then
              for cap in $(echo $CAP_ADD | tr ',' '\n'); do
                  CAP_OPTIONS+=" --cap-add=$cap"
              done
          fi

          # Extraire et traiter les ports exposés
          EXPOSE_PORTS=$(yq eval ".expose_ports | join(\",\")" <<< "$CONFIG" || true)
          if [ "$EXPOSE_PORTS" != "null" ] && [ -n "$EXPOSE_PORTS" ]; then
              for port in $(echo $EXPOSE_PORTS | tr ',' '\n'); do
                  EXPOSE_OPTIONS+=" --expose=$port"
              done
          fi

          RUN_AS_ROOT=$(yq eval ".run_as_root" <<< "$CONFIG")
          if [ -z "$RUN_AS_ROOT" ] || [ "$RUN_AS_ROOT" = "null" ]; then
            RUN_AS_ROOT=false
          fi

          if [ "$RUN_AS_ROOT" = true ]; then
            docker run -d --user root $CAP_OPTIONS --name $CONTAINER_NAME  $EXPOSE_OPTIONS $ENV_VARS ${{ matrix.service }}:$TAG
          else
            docker run -d $CAP_OPTIONS --name $CONTAINER_NAME $ENV_VARS ${{ matrix.service }}:$TAG
          fi

          NETWORK_ALIASES=$(yq eval ".network-alias // []" <<< "$CONFIG" || echo "")
          # Ajout des alias réseau après le démarrage du conteneur
          if [ -n "$NETWORK_ALIASES" ] && [ "$NETWORK_ALIASES" != "null" ]; then
              for alias in $(echo "$NETWORK_ALIASES" | yq eval '.[]' - 2>/dev/null); do
                  docker network connect --alias "$alias" "$NETWORK_NAME" "$CONTAINER_NAME" || echo "Erreur lors de l'ajout de l'alias $alias"
              done
          fi

  prune-unused-images:
    runs-on: [self-hosted, phil-host]
    needs: start-containers
    steps:
      - name: Prune Docker images
        run: |
          echo "Removing all unused images..."
          docker system prune -f

  health-check-containers:
    runs-on: [self-hosted, phil-host]
    needs: start-containers
    strategy:
      matrix:
        service: [vault, consul, mongodb, api-mongodb, postgresql, api-postgresql, api-gateway, frontend, reverse-proxy, minio, api-minio, api-processing, api-image-processing, api-text-processing, mlflow, prometheus, grafana, alertmanager, redis, airflow-worker,airflow-scheduler,airflow-triggerer,airflow-api-server,airflow-dag-processor]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get version from file
        id: get_version
        run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT

      - name: Perform health checks
        run: |
          set +e
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          NETWORK_NAME="network-${BRANCH_NAME}"
          SERVICE="${{ matrix.service }}"

          # Initialiser des tableaux pour stocker les URLs et les codes attendus
          URLS=()
          EXPECTED_CODES=()

          # Récupérer tous les couples URL et code attendu
          while IFS= read -r check; do
            # Extraire les valeurs pour url et expected_code
            URL=$(yq eval '.url' <<< "$check")
            EXPECTED_CODE=$(yq eval '.expected_code' <<< "$check")

            # Ajouter URL au tableau si elle n'est pas nulle
            if [ -n "$URL" ] && [ "$URL" != "null" ]; then
              URLS+=("$URL")
            fi

            # Ajouter expected_code au tableau s'il n'est pas nul
            if [ -n "$EXPECTED_CODE" ] && [ "$EXPECTED_CODE" != "null" ]; then
              EXPECTED_CODES+=("$EXPECTED_CODE")
            fi
          done < <(yq eval ".services[\"$SERVICE\"].health_check.urls | .[]" "services_config.yaml")

          # Boucle infinie pour vérifier la santé des URLs
          while true; do
            all_healthy=true
            for i in "${!URLS[@]}"; do
              # S'assurer que l'index existe pour les deux tableaux avant de procéder
              if [ "$i" -lt "${#EXPECTED_CODES[@]}" ]; then
                URL="${URLS[i]}"
                EXPECTED_CODE="${EXPECTED_CODES[i]}"
                echo "Checking URL: $URL with expected code: $EXPECTED_CODE"

                # Essayer d'obtenir le code HTTP
                if HTTP_CODE=$(docker run --rm --network "$NETWORK_NAME" --name "${{ matrix.service }}-$BRANCH_NAME-curl" curlimages/curl curl -s -k -o /dev/null -w "%{http_code}" "$URL"); then
                  # La commande a réussi
                  echo "HTTP Code: $HTTP_CODE"
                else
                  # La commande a échoué, définir HTTP_CODE à une valeur par défaut ou gérer l'erreur
                  HTTP_CODE=000
                  echo "Error occurred while accessing $URL"
                fi

                # Continuer avec la logique basée sur HTTP_CODE
                if [ "$HTTP_CODE" -ne "$EXPECTED_CODE" ]; then
                  echo "Waiting for $URL to be healthy. Current HTTP code: $HTTP_CODE"
                  all_healthy=false
                else
                  echo "$URL is healthy."
                fi
              else
                echo "Skipping check for URL ${URLS[i]} as there is no corresponding expected code."
                all_healthy=false
              fi
            done
            if [ "$all_healthy" = true ]; then
              echo "All URLs are healthy!"
              break
            fi
            sleep 1
          done
  
  lint:
    uses: ./.github/workflows/github-lint.yml
    needs: [start-containers]
    permissions:
      contents: 'read'
      id-token: 'write'
  
  tests:
    uses: ./.github/workflows/github-unit-tests.yml
    needs: [health-check-containers]
    permissions:
      contents: 'read'
      id-token: 'write'

  stop-containers:
    runs-on: [self-hosted, phil-host]
    needs: [tests, lint, start-containers]
    if: always()
    strategy:
      matrix:
        service: [vault, consul, mongodb, api-mongodb, postgresql, api-postgresql, api-gateway, frontend, reverse-proxy, minio, api-minio, api-processing, api-image-processing, api-text-processing, mlflow, prometheus, grafana, alertmanager, redis, airflow-worker,airflow-scheduler,airflow-triggerer,airflow-api-server,airflow-dag-processor]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get version from file
        id: get_version
        run: echo "VERSION=$(cat .version)" >> $GITHUB_OUTPUT
      - name: Stop and remove containers
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          # Arrêter et retirer le conteneur
          docker stop ${{ matrix.service }}-${BRANCH_NAME} || true
          docker rm ${{ matrix.service }}-${BRANCH_NAME} || true

  remove-network:
    runs-on: [self-hosted, phil-host]
    needs: stop-containers  
    steps:
      - name: Remove Docker network
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          NETWORK_NAME="network-${BRANCH_NAME}"
          if docker network inspect $NETWORK_NAME &> /dev/null; then
            docker network rm $NETWORK_NAME
          else
            echo "Réseau $NETWORK_NAME n'existe pas, pas besoin de le supprimer."
          fi
