name: AVR25 Rakuten MLOps - CI Unit tests
run-name: Unit testing AVR25 Rakuten MLOps actions started by ${{ github.actor }}
on:
  workflow_call:
jobs:
  tests-api-minio:
    runs-on: [self-hosted, phil-host, phil-host]
    needs: [health-check-containers]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Launch API Minio unit tests
        run: |
          sh scripts/launch_api_minio_tests.sh
      - name: Archive CI test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-test_results
          path: test_results/*test_result.xml
      - name: Archive CI code coverages
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-test_coverages
          path: test_results/*test_coverage.xml
  
  tests-api-mongodb:
    runs-on: [self-hosted, phil-host]
    needs: [health-check-containers]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Launch API MongoDB unit tests
        run: |
          sh scripts/launch_api_mongodb_tests.sh
      - name: Archive CI test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-test_results
          path: test_results/*test_result.xml
      - name: Archive CI code coverages
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-test_coverages
          path: test_results/*test_coverage.xml

  tests-api-postgresql:
    runs-on: [self-hosted, phil-host]
    needs: [health-check-containers]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Launch API PostGreSQL unit tests
        run: |
          sh scripts/launch_api_postgresql_tests.sh
      - name: Archive CI test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-test_results
          path: test_results/*test_result.xml
      - name: Archive CI code coverages
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-test_coverages
          path: test_results/*test_coverage.xml
  
  tests-api-gateway:
    runs-on: [self-hosted, phil-host]
    needs: [health-check-containers]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Launch API Gateway unit tests
        run: |
          sh scripts/launch_api_gateway_tests.sh
      - name: Archive CI test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-test_results
          path: test_results/*test_result.xml
      - name: Archive CI code coverages
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-test_coverages
          path: test_results/*test_coverage.xml