[pytest]
testpaths =
    test/api/test_hello.py
    test/api/test_auth.py
    test/api/internal/mongodb/entity/test_user.py
    test/api/internal/mongodb/entity/test_ad.py
    test/api/internal/mongodb/entity/test_category.py
    test/api/internal/mongodb/entity/test_ad_category.py
